-------------------------------------------------------------------------------
Test set: com.example.MainTest
-------------------------------------------------------------------------------
Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.100 s <<< FAILURE! -- in com.example.MainTest
com.example.MainTest.Function_11_should_return_XI -- Time elapsed: 0.009 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: "XI"
 but was: "VIIIIII"
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at com.example.MainTest.Function_11_should_return_XI(MainTest.java:71)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

